<a href="https://colab.research.google.com/github/zubairkhan882602-tech/zubair/blob/main/zubair_sql_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
url = 'https://raw.githubusercontent.com/zubairkhan882602-tech/zubair/refs/heads/main/Uber%20Request%20Data.csv'

ride_data = pd.read_csv(url)
print("Dataset loaded successfully!")
print("Total records:", len(ride_data))
ride_data.head()

Dataset loaded successfully!
Total records: 6745

,Request id,Pickup point,Driver id,Status,Request timestamp,Drop timestamp
0,619,Airport,1.0,Trip Completed,11/7/2016 11:51,11/7/2016 13:00
1,867,Airport,1.0,Trip Completed,11/7/2016 17:57,11/7/2016 18:47
2,1807,City,1.0,Trip Completed,12/7/2016 9:17,12/7/2016 9:58
3,2532,Airport,1.0,Trip Completed,12/7/2016 21:08,12/7/2016 22:03
4,3112,City,1.0,Trip Completed,13-07-2016 08:33:16,13-07-2016 09:25:47

In [21]:
import os

for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for file in files:
        if 'Uber' in file or 'uber' in file:
            print(os.path.join(root, file))

/content/drive/MyDrive/Uber CLEAN Data.xlsx
/content/drive/MyDrive/uber.db
/content/drive/MyDrive/Colab Notebooks/Uber_EDA_Zubair new

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [23]:
import os
os.listdir('/content/drive/MyDrive')

['51292C4B-D080-403B-85E5-66671456B0AE.jpeg',
 '37F7E8CD-7FFB-483E-9B25-E4420C43C429.jpeg',
 'EDD65F3C-262E-417D-BA36-0D6330B8674D.jpeg',
 '50A74755-3C28-4F42-9EC9-01AF554BF3B2.jpeg',
 '20531171-6CB1-4A9F-AE38-6FC72DEA7969.jpeg',
 '61405B1A-A1D9-4BED-89D8-BCC1FC6EF1EF.jpeg',
 'A75271A2-D2F2-4134-AD9F-BC7B522A460E.jpeg',
 'C666AA12-D69F-4BCD-ACAD-44AAAC34B090.jpeg',
 'image (2).jpg',
 'image (1).jpg',
 'image.jpg',
 'AD91BAF6-ABE5-4B2A-99DC-0138B6256386.jpeg',
 '5CD4CE77-2BF7-4A09-A89E-4A1A38791047.jpeg',
 '08BF4E7A-B677-4972-A13A-82A9A521E8FE.jpeg',
 '3DF15E27-0D90-4F22-9383-0613488B38D9.jpeg',
 'F05FB0F8-12A7-429E-BCF2-40809B4B53D0.jpeg',
 'C0A687FC-9B1F-4BCF-B51B-707425A9F9D8.jpeg',
 '3C719FFA-2696-470F-8A8C-43DD59562E9B.jpeg',
 'IMG_9068.PNG',
 'IMG_4426 (1).jpeg',
 'IMG_4426.jpeg',
 'IMG_6694.jpeg',
 'Create a vintage 1970s Bollywood-inspired photogra....gdoc',
 'IMG_0301.jpeg',
 'MOHD ZUBAIR KHAN_Resume.pdf',
 'Uber CLEAN Data.xlsx',
 'Colab Notebooks',
 'uber.db']

In [24]:
for item in os.listdir('/content/drive/MyDrive'):
    print(item)

51292C4B-D080-403B-85E5-66671456B0AE.jpeg
37F7E8CD-7FFB-483E-9B25-E4420C43C429.jpeg
EDD65F3C-262E-417D-BA36-0D6330B8674D.jpeg
50A74755-3C28-4F42-9EC9-01AF554BF3B2.jpeg
20531171-6CB1-4A9F-AE38-6FC72DEA7969.jpeg
61405B1A-A1D9-4BED-89D8-BCC1FC6EF1EF.jpeg
A75271A2-D2F2-4134-AD9F-BC7B522A460E.jpeg
C666AA12-D69F-4BCD-ACAD-44AAAC34B090.jpeg
image (2).jpg
image (1).jpg
image.jpg
AD91BAF6-ABE5-4B2A-99DC-0138B6256386.jpeg
5CD4CE77-2BF7-4A09-A89E-4A1A38791047.jpeg
08BF4E7A-B677-4972-A13A-82A9A521E8FE.jpeg
3DF15E27-0D90-4F22-9383-0613488B38D9.jpeg
F05FB0F8-12A7-429E-BCF2-40809B4B53D0.jpeg
C0A687FC-9B1F-4BCF-B51B-707425A9F9D8.jpeg
3C719FFA-2696-470F-8A8C-43DD59562E9B.jpeg
IMG_9068.PNG
IMG_4426 (1).jpeg
IMG_4426.jpeg
IMG_6694.jpeg
Create a vintage 1970s Bollywood-inspired photogra....gdoc
IMG_0301.jpeg
MOHD ZUBAIR KHAN_Resume.pdf
Uber CLEAN Data.xlsx
Colab Notebooks
uber.db

In [25]:
import os

os.listdir('/content/drive/MyDrive')

['51292C4B-D080-403B-85E5-66671456B0AE.jpeg',
 '37F7E8CD-7FFB-483E-9B25-E4420C43C429.jpeg',
 'EDD65F3C-262E-417D-BA36-0D6330B8674D.jpeg',
 '50A74755-3C28-4F42-9EC9-01AF554BF3B2.jpeg',
 '20531171-6CB1-4A9F-AE38-6FC72DEA7969.jpeg',
 '61405B1A-A1D9-4BED-89D8-BCC1FC6EF1EF.jpeg',
 'A75271A2-D2F2-4134-AD9F-BC7B522A460E.jpeg',
 'C666AA12-D69F-4BCD-ACAD-44AAAC34B090.jpeg',
 'image (2).jpg',
 'image (1).jpg',
 'image.jpg',
 'AD91BAF6-ABE5-4B2A-99DC-0138B6256386.jpeg',
 '5CD4CE77-2BF7-4A09-A89E-4A1A38791047.jpeg',
 '08BF4E7A-B677-4972-A13A-82A9A521E8FE.jpeg',
 '3DF15E27-0D90-4F22-9383-0613488B38D9.jpeg',
 'F05FB0F8-12A7-429E-BCF2-40809B4B53D0.jpeg',
 'C0A687FC-9B1F-4BCF-B51B-707425A9F9D8.jpeg',
 '3C719FFA-2696-470F-8A8C-43DD59562E9B.jpeg',
 'IMG_9068.PNG',
 'IMG_4426 (1).jpeg',
 'IMG_4426.jpeg',
 'IMG_6694.jpeg',
 'Create a vintage 1970s Bollywood-inspired photogra....gdoc',
 'IMG_0301.jpeg',
 'MOHD ZUBAIR KHAN_Resume.pdf',
 'Uber CLEAN Data.xlsx',
 'Colab Notebooks',
 'uber.db']

In [26]:
import pandas as pd

file_path = '/content/drive/MyDrive/Uber CLEAN Data.xlsx'

df = pd.read_excel(file_path)

print(df.head())

   Request id Pickup point  Driver id          Status   Request timestamp  \
0         619      Airport        1.0  Trip Completed 2016-07-11 11:51:00
1         867      Airport        1.0  Trip Completed 2016-07-11 17:57:00
2        1807         City        1.0  Trip Completed 2016-07-12 09:17:00
3        2532      Airport        1.0  Trip Completed 2016-07-12 21:08:00
4        3112         City        1.0  Trip Completed 2016-07-13 08:33:16

       Drop timestamp
0 2016-07-11 13:00:00
1 2016-07-11 18:47:00
2 2016-07-12 09:58:00
3 2016-07-12 22:03:00
4 2016-07-13 09:25:47

In [27]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os

for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for file in files:
        if file.endswith('.xlsx'):
            print(os.path.join(root, file))

Mounted at /content/drive
/content/drive/MyDrive/Uber CLEAN Data.xlsx

In [28]:
import pandas as pd
import sqlite3

# Clean column names
df.columns = df.columns.str.strip().str.replace(' ', '_')

# Create SQLite database
conn = sqlite3.connect('uber.db')

# Create table
df.to_sql('trips', conn, if_exists='replace', index=False)

print("✅ Database ready! Table 'trips' created.")

✅ Database ready! Table 'trips' created.

In [29]:
def run_query(sql, title=""):
    result = pd.read_sql_query(sql, conn)
    if title:
        print(f"\n{'='*50}")
        print(f"  {title}")
        print(f"{'='*50}")
    display(result)
    return result

In [30]:
run_query("""
    SELECT
        Status,
        COUNT(*) AS Total_Trips
    FROM trips
    GROUP BY Status
    ORDER BY Total_Trips DESC
""", title="Trip Count by Status")

==================================================
  Trip Count by Status
==================================================

              Status  Total_Trips
0     Trip Completed         2831
1  No Cars Available         2650
2          Cancelled         1264

              Status  Total_Trips
0     Trip Completed         2831
1  No Cars Available         2650
2          Cancelled         1264

In [31]:
run_query("""
    SELECT
        Status,
        COUNT(*) AS Total_Trips
    FROM trips
    GROUP BY Status
    ORDER BY Total_Trips DESC
""", title="Query 1 - Trip Count by Status");

==================================================
  Query 1 - Trip Count by Status
==================================================

              Status  Total_Trips
0     Trip Completed         2831
1  No Cars Available         2650
2          Cancelled         1264

In [32]:
cursor = conn.cursor()

cursor.execute("PRAGMA table_info(trips)")
print(cursor.fetchall())

[(0, 'Request_id', 'INTEGER', 0, None, 0), (1, 'Pickup_point', 'TEXT', 0, None, 0), (2, 'Driver_id', 'REAL', 0, None, 0), (3, 'Status', 'TEXT', 0, None, 0), (4, 'Request_timestamp', 'TIMESTAMP', 0, None, 0), (5, 'Drop_timestamp', 'TIMESTAMP', 0, None, 0)]

In [33]:
import pandas as pd

pd.read_sql("SELECT * FROM trips LIMIT 5", conn)

,Request_id,Pickup_point,Driver_id,Status,Request_timestamp,Drop_timestamp
0,619,Airport,1.0,Trip Completed,2016-07-11 11:51:00,2016-07-11 13:00:00
1,867,Airport,1.0,Trip Completed,2016-07-11 17:57:00,2016-07-11 18:47:00
2,1807,City,1.0,Trip Completed,2016-07-12 09:17:00,2016-07-12 09:58:00
3,2532,Airport,1.0,Trip Completed,2016-07-12 21:08:00,2016-07-12 22:03:00
4,3112,City,1.0,Trip Completed,2016-07-13 08:33:16,2016-07-13 09:25:47

In [34]:
print(df.columns.tolist())

['Request_id', 'Pickup_point', 'Driver_id', 'Status', 'Request_timestamp', 'Drop_timestamp']

In [35]:
df.to_sql('trips', conn, if_exists='replace', index=False)

6745

In [36]:
print(df.columns.tolist())

['Request_id', 'Pickup_point', 'Driver_id', 'Status', 'Request_timestamp', 'Drop_timestamp']

In [37]:
run_query("PRAGMA table_info(trips)")

   cid               name       type  notnull dflt_value  pk
0    0         Request_id    INTEGER        0       None   0
1    1       Pickup_point       TEXT        0       None   0
2    2          Driver_id       REAL        0       None   0
3    3             Status       TEXT        0       None   0
4    4  Request_timestamp  TIMESTAMP        0       None   0
5    5     Drop_timestamp  TIMESTAMP        0       None   0

   cid               name       type  notnull dflt_value  pk
0    0         Request_id    INTEGER        0       None   0
1    1       Pickup_point       TEXT        0       None   0
2    2          Driver_id       REAL        0       None   0
3    3             Status       TEXT        0       None   0
4    4  Request_timestamp  TIMESTAMP        0       None   0
5    5     Drop_timestamp  TIMESTAMP        0       None   0

In [38]:
print(df.columns.tolist())

['Request_id', 'Pickup_point', 'Driver_id', 'Status', 'Request_timestamp', 'Drop_timestamp']

In [39]:
for col in df.columns:
    print(col)

Request_id
Pickup_point
Driver_id
Status
Request_timestamp
Drop_timestamp

In [40]:
print(df.columns.tolist())

['Request_id', 'Pickup_point', 'Driver_id', 'Status', 'Request_timestamp', 'Drop_timestamp']

In [41]:
for col in df.columns:
    print(col)

Request_id
Pickup_point
Driver_id
Status
Request_timestamp
Drop_timestamp

In [42]:
['Request id',
 'Pickup point',
 'Driver id',
 'Status',
 'Request timestamp']

['Request id', 'Pickup point', 'Driver id', 'Status', 'Request timestamp']

In [43]:
for col in df.columns:
    if 'request' in col.lower():
        print(col)

Request_id
Request_timestamp

In [44]:
df['Request_timestamp'] = pd.to_datetime(df['Request_timestamp'])

df['Hour'] = df['Request_timestamp'].dt.hour

df.to_sql('trips', conn, if_exists='replace', index=False)

print("✅ Hour column created successfully!")

✅ Hour column created successfully!

In [45]:
print(df[['Request_timestamp','Hour']].head())

    Request_timestamp  Hour
0 2016-07-11 11:51:00    11
1 2016-07-11 17:57:00    17
2 2016-07-12 09:17:00     9
3 2016-07-12 21:08:00    21
4 2016-07-13 08:33:16     8

In [46]:
run_query("""
SELECT
    Hour,
    COUNT(*) AS Unfulfilled_Requests
FROM trips
WHERE Status IN ('Cancelled', 'No Cars Available')
GROUP BY Hour
ORDER BY Hour
""")

    Hour  Unfulfilled_Requests
0      0                    59
1      1                    60
2      2                    62
3      3                    58
4      4                   125
5      5                   260
6      6                   231
7      7                   232
8      8                   268
9      9                   258
10    10                   127
11    11                    56
12    12                    63
13    13                    71
14    14                    48
15    15                    69
16    16                    68
17    17                   267
18    18                   346
19    19                   307
20    20                   331
21    21                   307
22    22                   150
23    23                    91

    Hour  Unfulfilled_Requests
0      0                    59
1      1                    60
2      2                    62
3      3                    58
4      4                   125
5      5                   260
6      6                   231
7      7                   232
8      8                   268
9      9                   258
10    10                   127
11    11                    56
12    12                    63
13    13                    71
14    14                    48
15    15                    69
16    16                    68
17    17                   267
18    18                   346
19    19                   307
20    20                   331
21    21                   307
22    22                   150
23    23                    91

In [47]:
query = """
SELECT
    Hour,
    COUNT(*) AS Unfulfilled_Requests
FROM trips
WHERE Status IN ('Cancelled', 'No Cars Available')
GROUP BY Hour
ORDER BY Hour
"""

pd.read_sql_query(query, conn)

    Hour  Unfulfilled_Requests
0      0                    59
1      1                    60
2      2                    62
3      3                    58
4      4                   125
5      5                   260
6      6                   231
7      7                   232
8      8                   268
9      9                   258
10    10                   127
11    11                    56
12    12                    63
13    13                    71
14    14                    48
15    15                    69
16    16                    68
17    17                   267
18    18                   346
19    19                   307
20    20                   331
21    21                   307
22    22                   150
23    23                    91

In [48]:
df['Request_timestamp'] = pd.to_datetime(df['Request_timestamp'])

df['Hour'] = df['Request_timestamp'].dt.hour

df['Time_of_Day'] = df['Hour'].apply(
    lambda x: 'Morning' if 5 <= x < 12
    else 'Afternoon' if 12 <= x < 17
    else 'Evening' if 17 <= x < 21
    else 'Night'
)

# Database update
df.to_sql('trips', conn, if_exists='replace', index=False)

print("✅ Time_of_Day column created!")

✅ Time_of_Day column created!

In [49]:
print(df[['Hour','Time_of_Day']].head())

   Hour Time_of_Day
0    11     Morning
1    17     Evening
2     9     Morning
3    21       Night
4     8     Morning

In [50]:
query = """
SELECT
    Time_of_Day,
    COUNT(*) AS Unfulfilled_Requests
FROM trips
WHERE Status IN ('Cancelled', 'No Cars Available')
GROUP BY Time_of_Day
ORDER BY Unfulfilled_Requests DESC
"""

pd.read_sql_query(query, conn)

  Time_of_Day  Unfulfilled_Requests
0     Morning                  1432
1     Evening                  1251
2       Night                   912
3   Afternoon                   319

In [51]:
print(df.columns.tolist())

['Request_id', 'Pickup_point', 'Driver_id', 'Status', 'Request_timestamp', 'Drop_timestamp', 'Hour', 'Time_of_Day']

In [52]:
run_query("""
SELECT
    Pickup_point,
    Status,
    COUNT(*) AS Count
FROM trips
WHERE Status IN ('Cancelled', 'No Cars Available')
GROUP BY Pickup_point, Status
ORDER BY Pickup_point, Count DESC
""", title="Query 4 - Airport vs City Cancelled and No Cars")

==================================================
  Query 4 - Airport vs City Cancelled and No Cars
==================================================

  Pickup_point             Status  Count
0      Airport  No Cars Available   1713
1      Airport          Cancelled    198
2         City          Cancelled   1066
3         City  No Cars Available    937

  Pickup_point             Status  Count
0      Airport  No Cars Available   1713
1      Airport          Cancelled    198
2         City          Cancelled   1066
3         City  No Cars Available    937

In [53]:
run_query("""
SELECT
    Driver_id,
    COUNT(*) AS Cancellations
FROM trips
WHERE Status = 'Cancelled'
    AND Driver_id IS NOT NULL
GROUP BY Driver_id
ORDER BY Cancellations DESC
LIMIT 10
""", title="Query 5 - Top 10 Drivers by Cancellations")

==================================================
  Query 5 - Top 10 Drivers by Cancellations
==================================================

   Driver_id  Cancellations
0       84.0             12
1       54.0             11
2      206.0             10
3      142.0             10
4      267.0              9
5      210.0              9
6      166.0              9
7      138.0              9
8      114.0              9
9       27.0              9

   Driver_id  Cancellations
0       84.0             12
1       54.0             11
2      206.0             10
3      142.0             10
4      267.0              9
5      210.0              9
6      166.0              9
7      138.0              9
8      114.0              9
9       27.0              9

In [54]:
run_query("""
SELECT
    Pickup_point,
    COUNT(*) AS Total_Requests,
    SUM(CASE WHEN Status = 'Trip Completed' THEN 1 ELSE 0 END) AS Completed,
    ROUND(
        100.0 * SUM(CASE WHEN Status = 'Trip Completed' THEN 1 ELSE 0 END)
        / COUNT(*),
        1
    ) AS Completion_Rate_Pct
FROM trips
GROUP BY Pickup_point
ORDER BY Completion_Rate_Pct DESC
""", title="Query 6 - Completion Rate Airport vs City")

==================================================
  Query 6 - Completion Rate Airport vs City
==================================================

  Pickup_point  Total_Requests  Completed  Completion_Rate_Pct
0         City            3507       1504                 42.9
1      Airport            3238       1327                 41.0

  Pickup_point  Total_Requests  Completed  Completion_Rate_Pct
0         City            3507       1504                 42.9
1      Airport            3238       1327                 41.0

In [55]:
run_query("""
SELECT
    Pickup_point,
    Time_of_Day,
    COUNT(*) AS Problem_Requests
FROM trips
WHERE Status IN ('Cancelled', 'No Cars Available')
GROUP BY Pickup_point, Time_of_Day
ORDER BY Problem_Requests DESC
LIMIT 10
""", title="Query 7 - Worst Pickup Point and Time Slot Combos")

==================================================
  Query 7 - Worst Pickup Point and Time Slot Combos
==================================================

  Pickup_point Time_of_Day  Problem_Requests
0         City     Morning              1351
1      Airport     Evening              1145
2      Airport       Night               571
3         City       Night               341
4         City   Afternoon               205
5      Airport   Afternoon               114
6         City     Evening               106
7      Airport     Morning                81

  Pickup_point Time_of_Day  Problem_Requests
0         City     Morning              1351
1      Airport     Evening              1145
2      Airport       Night               571
3         City       Night               341
4         City   Afternoon               205
5      Airport   Afternoon               114
6         City     Evening               106
7      Airport     Morning                81