In [9]:
import os

for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for file in files:
        if 'Uber' in file or 'uber' in file:
            print(os.path.join(root, file))

/content/drive/MyDrive/Uber CLEAN Data.xlsx

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os
os.listdir('/content/drive/MyDrive')

['Colab Notebooks',
 '51292C4B-D080-403B-85E5-66671456B0AE.jpeg',
 '37F7E8CD-7FFB-483E-9B25-E4420C43C429.jpeg',
 'EDD65F3C-262E-417D-BA36-0D6330B8674D.jpeg',
 '50A74755-3C28-4F42-9EC9-01AF554BF3B2.jpeg',
 '20531171-6CB1-4A9F-AE38-6FC72DEA7969.jpeg',
 '61405B1A-A1D9-4BED-89D8-BCC1FC6EF1EF.jpeg',
 'A75271A2-D2F2-4134-AD9F-BC7B522A460E.jpeg',
 'C666AA12-D69F-4BCD-ACAD-44AAAC34B090.jpeg',
 'image (2).jpg',
 'image (1).jpg',
 'image.jpg',
 'AD91BAF6-ABE5-4B2A-99DC-0138B6256386.jpeg',
 '5CD4CE77-2BF7-4A09-A89E-4A1A38791047.jpeg',
 '08BF4E7A-B677-4972-A13A-82A9A521E8FE.jpeg',
 '3DF15E27-0D90-4F22-9383-0613488B38D9.jpeg',
 'F05FB0F8-12A7-429E-BCF2-40809B4B53D0.jpeg',
 'C0A687FC-9B1F-4BCF-B51B-707425A9F9D8.jpeg',
 '3C719FFA-2696-470F-8A8C-43DD59562E9B.jpeg',
 'IMG_9068.PNG',
 'IMG_4426 (1).jpeg',
 'IMG_4426.jpeg',
 'IMG_6694.jpeg',
 'Create a vintage 1970s Bollywood-inspired photogra....gdoc',
 'IMG_0301.jpeg',
 'MOHD ZUBAIR KHAN_Resume.pdf',
 'Uber CLEAN Data.xlsx']

In [4]:
for item in os.listdir('/content/drive/MyDrive'):
    print(item)

Colab Notebooks
51292C4B-D080-403B-85E5-66671456B0AE.jpeg
37F7E8CD-7FFB-483E-9B25-E4420C43C429.jpeg
EDD65F3C-262E-417D-BA36-0D6330B8674D.jpeg
50A74755-3C28-4F42-9EC9-01AF554BF3B2.jpeg
20531171-6CB1-4A9F-AE38-6FC72DEA7969.jpeg
61405B1A-A1D9-4BED-89D8-BCC1FC6EF1EF.jpeg
A75271A2-D2F2-4134-AD9F-BC7B522A460E.jpeg
C666AA12-D69F-4BCD-ACAD-44AAAC34B090.jpeg
image (2).jpg
image (1).jpg
image.jpg
AD91BAF6-ABE5-4B2A-99DC-0138B6256386.jpeg
5CD4CE77-2BF7-4A09-A89E-4A1A38791047.jpeg
08BF4E7A-B677-4972-A13A-82A9A521E8FE.jpeg
3DF15E27-0D90-4F22-9383-0613488B38D9.jpeg
F05FB0F8-12A7-429E-BCF2-40809B4B53D0.jpeg
C0A687FC-9B1F-4BCF-B51B-707425A9F9D8.jpeg
3C719FFA-2696-470F-8A8C-43DD59562E9B.jpeg
IMG_9068.PNG
IMG_4426 (1).jpeg
IMG_4426.jpeg
IMG_6694.jpeg
Create a vintage 1970s Bollywood-inspired photogra....gdoc
IMG_0301.jpeg
MOHD ZUBAIR KHAN_Resume.pdf
Uber CLEAN Data.xlsx

In [6]:
import os

os.listdir('/content/drive/MyDrive')

['Colab Notebooks',
 '51292C4B-D080-403B-85E5-66671456B0AE.jpeg',
 '37F7E8CD-7FFB-483E-9B25-E4420C43C429.jpeg',
 'EDD65F3C-262E-417D-BA36-0D6330B8674D.jpeg',
 '50A74755-3C28-4F42-9EC9-01AF554BF3B2.jpeg',
 '20531171-6CB1-4A9F-AE38-6FC72DEA7969.jpeg',
 '61405B1A-A1D9-4BED-89D8-BCC1FC6EF1EF.jpeg',
 'A75271A2-D2F2-4134-AD9F-BC7B522A460E.jpeg',
 'C666AA12-D69F-4BCD-ACAD-44AAAC34B090.jpeg',
 'image (2).jpg',
 'image (1).jpg',
 'image.jpg',
 'AD91BAF6-ABE5-4B2A-99DC-0138B6256386.jpeg',
 '5CD4CE77-2BF7-4A09-A89E-4A1A38791047.jpeg',
 '08BF4E7A-B677-4972-A13A-82A9A521E8FE.jpeg',
 '3DF15E27-0D90-4F22-9383-0613488B38D9.jpeg',
 'F05FB0F8-12A7-429E-BCF2-40809B4B53D0.jpeg',
 'C0A687FC-9B1F-4BCF-B51B-707425A9F9D8.jpeg',
 '3C719FFA-2696-470F-8A8C-43DD59562E9B.jpeg',
 'IMG_9068.PNG',
 'IMG_4426 (1).jpeg',
 'IMG_4426.jpeg',
 'IMG_6694.jpeg',
 'Create a vintage 1970s Bollywood-inspired photogra....gdoc',
 'IMG_0301.jpeg',
 'MOHD ZUBAIR KHAN_Resume.pdf',
 'Uber CLEAN Data.xlsx']

In [7]:
import pandas as pd

file_path = '/content/drive/MyDrive/Uber CLEAN Data.xlsx'

df = pd.read_excel(file_path)

print(df.head())

   Request id Pickup point  Driver id          Status   Request timestamp  \
0         619      Airport        1.0  Trip Completed 2016-07-11 11:51:00
1         867      Airport        1.0  Trip Completed 2016-07-11 17:57:00
2        1807         City        1.0  Trip Completed 2016-07-12 09:17:00
3        2532      Airport        1.0  Trip Completed 2016-07-12 21:08:00
4        3112         City        1.0  Trip Completed 2016-07-13 08:33:16

       Drop timestamp
0 2016-07-11 13:00:00
1 2016-07-11 18:47:00
2 2016-07-12 09:58:00
3 2016-07-12 22:03:00
4 2016-07-13 09:25:47

In [12]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os

for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for file in files:
        if file.endswith('.xlsx'):
            print(os.path.join(root, file))

Mounted at /content/drive
/content/drive/MyDrive/Uber CLEAN Data.xlsx

In [13]:
# Clean column names
df.columns = df.columns.str.strip().str.replace(' ', '_')

# Create SQLite database
conn = sqlite3.connect('uber.db')
df.to_sql('trips', conn, if_exists='replace', index=False)

print("✅ Database ready! Table 'trips' created.")

✅ Database ready! Table 'trips' created.

In [14]:
# Clean column names (removes spaces)
df.columns = df.columns.str.strip().str.replace(' ', '_')

# Create SQLite database
conn = sqlite3.connect('uber.db')
df.to_sql('trips', conn, if_exists='replace', index=False)

print("✅ Database ready! Table 'trips' created.")

✅ Database ready! Table 'trips' created.

In [16]:
import shutil

shutil.copy('uber.db', '/content/drive/MyDrive/uber.db')

print("✅ Database saved to Drive!")

✅ Database saved to Drive!

In [18]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('/content/drive/MyDrive/uber.db')

query = "SELECT * FROM trips LIMIT 5"

df = pd.read_sql_query(query, conn)

df

,Request_id,Pickup_point,Driver_id,Status,Request_timestamp,Drop_timestamp
0,619,Airport,1.0,Trip Completed,2016-07-11 11:51:00,2016-07-11 13:00:00
1,867,Airport,1.0,Trip Completed,2016-07-11 17:57:00,2016-07-11 18:47:00
2,1807,City,1.0,Trip Completed,2016-07-12 09:17:00,2016-07-12 09:58:00
3,2532,Airport,1.0,Trip Completed,2016-07-12 21:08:00,2016-07-12 22:03:00
4,3112,City,1.0,Trip Completed,2016-07-13 08:33:16,2016-07-13 09:25:47

In [20]:
conn = sqlite3.connect('uber.db')

df.to_sql('trips', conn, if_exists='replace', index=False)

import shutil

shutil.copy('uber.db', '/content/drive/MyDrive/uber.db')

print("✅ Database ready and saved to Drive!")

✅ Database ready and saved to Drive!

In [22]:
def run_query(sql, title=""):
    result = pd.read_sql_query(sql, conn)
    if title:
        print(f"\n{'='*50}")
        print(f"  {title}")
        print(f"{'='*50}")
    display(result)
    return result

In [23]:
run_query("""
    SELECT
        Status,
        COUNT(*) AS Total_Trips
    FROM trips
    GROUP BY Status
    ORDER BY Total_Trips DESC
""", title="Trip Count by Status")

==================================================
  Trip Count by Status
==================================================

           Status  Total_Trips
0  Trip Completed            5

           Status  Total_Trips
0  Trip Completed            5

In [25]:
run_query("""
    SELECT
        Status,
        COUNT(*) AS Total_Trips
    FROM trips
    GROUP BY Status
    ORDER BY Total_Trips DESC
""", title="Query 1 - Trip Count by Status");

==================================================
  Query 1 - Trip Count by Status
==================================================

           Status  Total_Trips
0  Trip Completed            5

In [27]:
cursor = conn.cursor()

cursor.execute("PRAGMA table_info(trips)")
print(cursor.fetchall())

[(0, 'Request_id', 'INTEGER', 0, None, 0), (1, 'Pickup_point', 'TEXT', 0, None, 0), (2, 'Driver_id', 'REAL', 0, None, 0), (3, 'Status', 'TEXT', 0, None, 0), (4, 'Request_timestamp', 'TEXT', 0, None, 0), (5, 'Drop_timestamp', 'TEXT', 0, None, 0)]

In [28]:
import pandas as pd

pd.read_sql("SELECT * FROM trips LIMIT 5", conn)

,Request_id,Pickup_point,Driver_id,Status,Request_timestamp,Drop_timestamp
0,619,Airport,1.0,Trip Completed,2016-07-11 11:51:00,2016-07-11 13:00:00
1,867,Airport,1.0,Trip Completed,2016-07-11 17:57:00,2016-07-11 18:47:00
2,1807,City,1.0,Trip Completed,2016-07-12 09:17:00,2016-07-12 09:58:00
3,2532,Airport,1.0,Trip Completed,2016-07-12 21:08:00,2016-07-12 22:03:00
4,3112,City,1.0,Trip Completed,2016-07-13 08:33:16,2016-07-13 09:25:47

In [29]:
print(df.columns.tolist())

['Request_id', 'Pickup_point', 'Driver_id', 'Status', 'Request_timestamp', 'Drop_timestamp']

In [31]:
df.to_sql('trips', conn, if_exists='replace', index=False)

5

In [35]:
print(df.columns.tolist())

['Request_id', 'Pickup_point', 'Driver_id', 'Status', 'Request_timestamp', 'Drop_timestamp']

In [36]:
run_query("PRAGMA table_info(trips)")

   cid               name     type  notnull dflt_value  pk
0    0         Request_id  INTEGER        0       None   0
1    1       Pickup_point     TEXT        0       None   0
2    2          Driver_id     REAL        0       None   0
3    3             Status     TEXT        0       None   0
4    4  Request_timestamp     TEXT        0       None   0
5    5     Drop_timestamp     TEXT        0       None   0

   cid               name     type  notnull dflt_value  pk
0    0         Request_id  INTEGER        0       None   0
1    1       Pickup_point     TEXT        0       None   0
2    2          Driver_id     REAL        0       None   0
3    3             Status     TEXT        0       None   0
4    4  Request_timestamp     TEXT        0       None   0
5    5     Drop_timestamp     TEXT        0       None   0

In [38]:
print(df.columns.tolist())

['Request_id', 'Pickup_point', 'Driver_id', 'Status', 'Request_timestamp', 'Drop_timestamp']

In [39]:
for col in df.columns:
    print(col)

Request_id
Pickup_point
Driver_id
Status
Request_timestamp
Drop_timestamp

In [41]:
print(df.columns.tolist())

['Request_id', 'Pickup_point', 'Driver_id', 'Status', 'Request_timestamp', 'Drop_timestamp']

In [42]:
for col in df.columns:
    print(col)

Request_id
Pickup_point
Driver_id
Status
Request_timestamp
Drop_timestamp

In [43]:
['Request id',
 'Pickup point',
 'Driver id',
 'Status',
 'Request timestamp']

['Request id', 'Pickup point', 'Driver id', 'Status', 'Request timestamp']

In [44]:
for col in df.columns:
    if 'request' in col.lower():
        print(col)

Request_id
Request_timestamp

In [45]:
df['Request_timestamp'] = pd.to_datetime(df['Request_timestamp'])

df['Hour'] = df['Request_timestamp'].dt.hour

df.to_sql('trips', conn, if_exists='replace', index=False)

print("✅ Hour column created successfully!")

✅ Hour column created successfully!

In [46]:
print(df[['Request_timestamp','Hour']].head())

    Request_timestamp  Hour
0 2016-07-11 11:51:00    11
1 2016-07-11 17:57:00    17
2 2016-07-12 09:17:00     9
3 2016-07-12 21:08:00    21
4 2016-07-13 08:33:16     8

In [47]:
run_query("""
SELECT
    Hour,
    COUNT(*) AS Unfulfilled_Requests
FROM trips
WHERE Status IN ('Cancelled', 'No Cars Available')
GROUP BY Hour
ORDER BY Hour
""")

Empty DataFrame
Columns: [Hour, Unfulfilled_Requests]
Index: []

Empty DataFrame
Columns: [Hour, Unfulfilled_Requests]
Index: []

In [48]:
query = """
SELECT
    Hour,
    COUNT(*) AS Unfulfilled_Requests
FROM trips
WHERE Status IN ('Cancelled', 'No Cars Available')
GROUP BY Hour
ORDER BY Hour
"""

pd.read_sql_query(query, conn)

Empty DataFrame
Columns: [Hour, Unfulfilled_Requests]
Index: []

In [50]:
df['Request_timestamp'] = pd.to_datetime(df['Request_timestamp'])

df['Hour'] = df['Request_timestamp'].dt.hour

df['Time_of_Day'] = df['Hour'].apply(
    lambda x: 'Morning' if 5 <= x < 12
    else 'Afternoon' if 12 <= x < 17
    else 'Evening' if 17 <= x < 21
    else 'Night'
)

# Database update
df.to_sql('trips', conn, if_exists='replace', index=False)

print("✅ Time_of_Day column created!")

✅ Time_of_Day column created!

In [51]:
print(df[['Hour','Time_of_Day']].head())

   Hour Time_of_Day
0    11     Morning
1    17     Evening
2     9     Morning
3    21       Night
4     8     Morning

In [52]:
query = """
SELECT
    Time_of_Day,
    COUNT(*) AS Unfulfilled_Requests
FROM trips
WHERE Status IN ('Cancelled', 'No Cars Available')
GROUP BY Time_of_Day
ORDER BY Unfulfilled_Requests DESC
"""

pd.read_sql_query(query, conn)

Empty DataFrame
Columns: [Time_of_Day, Unfulfilled_Requests]
Index: []

In [53]:
print(df.columns.tolist())

['Request_id', 'Pickup_point', 'Driver_id', 'Status', 'Request_timestamp', 'Drop_timestamp', 'Hour', 'Time_of_Day']

In [54]:
run_query("""
SELECT
    Pickup_point,
    Status,
    COUNT(*) AS Count
FROM trips
WHERE Status IN ('Cancelled', 'No Cars Available')
GROUP BY Pickup_point, Status
ORDER BY Pickup_point, Count DESC
""", title="Query 4 - Airport vs City Cancelled and No Cars")

==================================================
  Query 4 - Airport vs City Cancelled and No Cars
==================================================

Empty DataFrame
Columns: [Pickup_point, Status, Count]
Index: []

Empty DataFrame
Columns: [Pickup_point, Status, Count]
Index: []

In [55]:
run_query("""
SELECT
    Driver_id,
    COUNT(*) AS Cancellations
FROM trips
WHERE Status = 'Cancelled'
    AND Driver_id IS NOT NULL
GROUP BY Driver_id
ORDER BY Cancellations DESC
LIMIT 10
""", title="Query 5 - Top 10 Drivers by Cancellations")

==================================================
  Query 5 - Top 10 Drivers by Cancellations
==================================================

Empty DataFrame
Columns: [Driver_id, Cancellations]
Index: []

Empty DataFrame
Columns: [Driver_id, Cancellations]
Index: []

In [56]:
run_query("""
SELECT
    Pickup_point,
    COUNT(*) AS Total_Requests,
    SUM(CASE WHEN Status = 'Trip Completed' THEN 1 ELSE 0 END) AS Completed,
    ROUND(
        100.0 * SUM(CASE WHEN Status = 'Trip Completed' THEN 1 ELSE 0 END)
        / COUNT(*),
        1
    ) AS Completion_Rate_Pct
FROM trips
GROUP BY Pickup_point
ORDER BY Completion_Rate_Pct DESC
""", title="Query 6 - Completion Rate Airport vs City")

==================================================
  Query 6 - Completion Rate Airport vs City
==================================================

  Pickup_point  Total_Requests  Completed  Completion_Rate_Pct
0         City               2          2                100.0
1      Airport               3          3                100.0

  Pickup_point  Total_Requests  Completed  Completion_Rate_Pct
0         City               2          2                100.0
1      Airport               3          3                100.0

In [57]:
run_query("""
SELECT
    Pickup_point,
    Time_of_Day,
    COUNT(*) AS Problem_Requests
FROM trips
WHERE Status IN ('Cancelled', 'No Cars Available')
GROUP BY Pickup_point, Time_of_Day
ORDER BY Problem_Requests DESC
LIMIT 10
""", title="Query 7 - Worst Pickup Point and Time Slot Combos")

==================================================
  Query 7 - Worst Pickup Point and Time Slot Combos
==================================================

Empty DataFrame
Columns: [Pickup_point, Time_of_Day, Problem_Requests]
Index: []

Empty DataFrame
Columns: [Pickup_point, Time_of_Day, Problem_Requests]
Index: []